homeassistant:
  name: HASS Controller
  country: NL
  time_zone: Europe/Amsterdam
  unit_system: metric

default_config:

logger:
  default: info
  logs:
    custom_components.heatpump_controller: debug

climate:
  - platform: heatpump_controller
    threshold_before_heat: 0.07
    threshold_before_off: 0.007
    threshold_room_needs_heat: 0.3
    rooms:
      - sensor: climate.living_room_thermostat
        weight: 1.5
      - sensor: climate.bedroom_thermostat
        weight: 1.0
