homeassistant:
  name: HASS Controller
  country: NL
  time_zone: Europe/Amsterdam
  unit_system: metric

default_config:

logger:
  default: info
  logs:
    custom_components.heatpump_controller: debug

heatpump_controller:
  - on_off_switch: switch.heatpump_power
  - threshold_before_heat: 0.07
  - threshold_before_off: 0.007
  - threshold_room_needs_heat: 0.3
  - outdoor_sensor: sensor.outdoor_temperature
  - outdoor_thresholds:
      # Cold weather (< -5째C): more aggressive heating
      - min_temp: -100
        max_temp: -5
        threshold_before_heat: 0.05
        threshold_before_off: 0.005
      # Moderate weather (-5째C to 10째C): standard thresholds
      - min_temp: -5
        max_temp: 10
        threshold_before_heat: 0.07
        threshold_before_off: 0.007
      # Mild weather (>= 10째C): less aggressive heating
      - min_temp: 10
        threshold_before_heat: 0.10
        threshold_before_off: 0.01
  - rooms:
      - sensor: climate.living_room_thermostat
        weight: 1.5
      - sensor: climate.bedroom_thermostat
        weight: 1.0

