homeassistant:
  name: HASS Controller
  country: NL
  time_zone: Europe/Amsterdam
  unit_system: metric

default_config:

logger:
  default: info
  logs:
    custom_components.heatpump_controller: debug

heatpump_controller:
  - on_off_switch: switch.heatpump_power
  - threshold_before_heat: 0.07
  - threshold_before_off: 0.007
  - threshold_room_needs_heat: 0.3
  - outdoor_sensor: sensor.outdoor_temperature
  - outdoor_thresholds:
      - max_temp: 2 # Always on
        threshold_before_heat: 0.00
        threshold_before_off: 0.000
      - min_temp: 2
        max_temp: 7
        threshold_before_heat: 0.03
        threshold_before_off: 0.003
      - min_temp: 7
        threshold_before_heat: 0.07
        threshold_before_off: 0.007
  - rooms:
      - sensor: climate.living_room_thermostat
        weight: 1.5
      - sensor: climate.bedroom_thermostat
        weight: 1.0

